# Welcome to Jekyll!

# Site settings
title: DrupalTools
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://drupaltools.com" # the base hostname & protocol for your site
copyright: '<a href="https://www.drupal.org">Drupal</a> is a <a href="http://drupal.com/trademark">registered trademark</a> of <a href="http://buytaert.net">Dries Buytaert</a>.'

# Build settings
markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass
